name: sgn
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  mobx: 1.1.1
  provider: 4.0.5+1
  cloud_firestore: 0.13.5
  google_fonts: 1.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.3
  url_launcher: 5.4.5
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ui/

